name: 'run test'

on:
  schedule:
    - cron: '0 12 * * *' #中午12:00执行，修改时注意时区
  watch:
    types: started
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 执行test
      run: bash ./run_test.sh
