name: 'run BiliExp'

on:
  schedule:
    - cron: '0 12 * * *' #中午12:00执行，修改时注意时区
  watch:
    types: started
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    if: github.repository != 'happy888888/BiliExp' || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v2

    - name: 执行BiliExp
      run: bash ./run_test.sh
